spring:
  profiles:
    include:
      - db
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  level:
    com.springboot.study: info

jwt:
  secret: "Q4NSl604sgyHJj1qwEkR3ycUeR4uUAt7WJraD7EN3O9DVM4yyYuHxMEbSF4XXyYJkal13eqgB0F7Bq4HDLXORWLSDLXORWLSDLXORWLS"