spring:
  profiles:
    include:
      - db
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  level:
    com.springboot.study: debug

jwt:
  secret: "rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY8643"